pyaggr3g470r/controllers/article.py
import re
import logging
from sqlalchemy import func

from bootstrap import db
from .abstract import AbstractController
from pyaggr3g470r.controllers import FeedController
from pyaggr3g470r.models import Article

logger = logging.getLogger(__name__)


class ArticleController(AbstractController):
    _db_cls = Article

    def get(self, **filters):
        article = super(ArticleController, self).get(**filters)
        if not article.readed:
            self.update({'id': article.id}, {'readed': True})
        return article

    def challenge(self, ids):
        """Will return each id that wasn't found in the database."""
        for id_ in ids:
            if self.read(**id_).first():
                continue
            yield id_

    def count_by_feed(self, **filters):
        if self.user_id:
            filters['user_id'] = self.user_id
        return dict(db.session.query(Article.feed_id, func.count(Article.id))
                              .filter(*self._to_filters(**filters))
                              .group_by(Article.feed_id).all())

    def count_by_user_id(self, **filters):
        return dict(db.session.query(Article.user_id,
                                            func.count(Article.id))
                              .filter(*self._to_filters(**filters))
                              .group_by(Article.user_id).all())

    def create(self, **attrs):
        # handling special denorm for article rights
        assert 'feed_id' in attrs
        feed = FeedController(
                attrs.get('user_id', self.user_id)).get(id=attrs['feed_id'])
        if 'user_id' in attrs:
            assert feed.user_id == attrs['user_id'] or self.user_id is None
        attrs['user_id'] = feed.user_id

        # handling feed's filters
        for filter_ in feed.filters or []:
            match = False
            if filter_.get('type') == 'regex':
                match = re.match(filter_['pattern'], attrs.get('title', ''))
            elif filter_.get('type') == 'simple match':
                match = filter_['pattern'] in attrs.get('title', '')
            take_action = match and filter_.get('action on') == 'match' \
                    or not match and filter_.get('action on') == 'no match'

            if not take_action:
                continue

            if filter_.get('action') == 'mark as read':
                attrs['readed'] = True
                logger.warn("article %s will be created as read",
                            attrs['link'])
            elif filter_.get('action') == 'mark as favorite':
                attrs['like'] = True
                logger.warn("article %s will be created as liked",
                            attrs['link'])

        return super().create(**attrs)

pyaggr3g470r/controllers/feed.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

# pyAggr3g470r - A Web based news aggregator.
# Copyright (C) 2010-2015  Cédric Bonhomme - https://www.cedricbonhomme.org
#
# For more information : https://bitbucket.org/cedricbonhomme/pyaggr3g470r/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
from datetime import datetime, timedelta

import conf
from .abstract import AbstractController
from .icon import IconController
from pyaggr3g470r.models import Feed

logger = logging.getLogger(__name__)
DEFAULT_LIMIT = 5
DEFAULT_REFRESH_RATE = 60
DEFAULT_MAX_ERROR = conf.DEFAULT_MAX_ERROR


class FeedController(AbstractController):
    _db_cls = Feed

    def list_late(self, max_last, max_error=DEFAULT_MAX_ERROR,
                  limit=DEFAULT_LIMIT):
        return [feed for feed in self.read(
                            error_count__lt=max_error, enabled=True,
                            last_retrieved__lt=max_last)
                                .order_by('Feed.last_retrieved')
                                .limit(limit)]

    def list_fetchable(self, max_error=DEFAULT_MAX_ERROR, limit=DEFAULT_LIMIT,
                       refresh_rate=DEFAULT_REFRESH_RATE):
        now = datetime.now()
        max_last = now - timedelta(minutes=refresh_rate)
        feeds = self.list_late(max_last, max_error, limit)
        if feeds:
            self.update({'id__in': [feed.id for feed in feeds]},
                        {'last_retrieved': now})
        return feeds

    def _ensure_icon(self, attrs):
        if not attrs.get('icon_url'):
            return
        icon_contr = IconController()
        if not icon_contr.read(url=attrs['icon_url']).count():
            icon_contr.create(**{'url': attrs['icon_url']})

    def create(self, **attrs):
        self._ensure_icon(attrs)
        return super().create(**attrs)

    def update(self, filters, attrs):
        self._ensure_icon(attrs)
        return super().update(filters, attrs)

pyaggr3g470r/views/article.py
#! /usr/bin/env python
# -*- coding: utf-8 -

from flask import Blueprint, g, render_template, redirect

from pyaggr3g470r import controllers, utils
from pyaggr3g470r.lib.view_utils import etag_match
from pyaggr3g470r.decorators import pyagg_default_decorator

articles_bp = Blueprint('articles', __name__, url_prefix='/articles')
article_bp = Blueprint('article', __name__, url_prefix='/article')


@article_bp.route('/redirect/<int:article_id>', methods=['GET'])
@pyagg_default_decorator
def redirect_to_article(article_id):
    article = controllers.ArticleController(g.user.id).get(id=article_id)
    return redirect(article.link)


@article_bp.route('/<int:article_id>', methods=['GET'])
@pyagg_default_decorator
@etag_match
def article(article_id=None):
    """
    Presents the content of an article.
    """
    article = controllers.ArticleController(g.user.id).get(id=article_id)
    previous_article = article.previous_article()
    if previous_article is None:
        previous_article = article.source.articles[0]
    next_article = article.next_article()
    if next_article is None:
        next_article = article.source.articles[-1]

    return render_template('article.html',
                           head_titles=[utils.clear_string(article.title)],
                           article=article,
                           previous_article=previous_article,
                           next_article=next_article)

pyaggr3g470r/views/feed.py
#! /usr/bin/env python
# -*- coding: utf-8 -
import base64
import requests.exceptions
from hashlib import md5
from datetime import datetime, timedelta
from sqlalchemy import desc
from werkzeug.exceptions import BadRequest

from flask import Blueprint, g, render_template, flash, \
                  redirect, request, url_for, Response
from flask.ext.babel import gettext
from flask.ext.login import login_required

import conf
from pyaggr3g470r import utils
from pyaggr3g470r.lib.view_utils import etag_match
from pyaggr3g470r.lib.feed_utils import construct_feed_from
from pyaggr3g470r.forms import AddFeedForm
from pyaggr3g470r.controllers import FeedController, ArticleController

feeds_bp = Blueprint('feeds', __name__, url_prefix='/feeds')
feed_bp = Blueprint('feed', __name__, url_prefix='/feed')


@feeds_bp.route('/', methods=['GET'])
@login_required
@etag_match
def feeds():
    "Lists the subscribed  feeds in a table."
    art_contr = ArticleController(g.user.id)
    return render_template('feeds.html',
            feeds=FeedController(g.user.id).read(),
            unread_article_count=art_contr.count_by_feed(readed=False),
            article_count=art_contr.count_by_feed())


@feed_bp.route('/<int:feed_id>', methods=['GET'])
@login_required
@etag_match
def feed(feed_id=None):
    "Presents detailed information about a feed."
    feed = FeedController(g.user.id).get(id=feed_id)
    word_size = 6
    articles = ArticleController(g.user.id) \
            .read(feed_id=feed_id) \
            .order_by(desc("Article.date")).all()
    top_words = utils.top_words(articles, n=50, size=int(word_size))
    tag_cloud = utils.tag_cloud(top_words)

    today = datetime.now()
    try:
        last_article = articles[0].date
        first_article = articles[-1].date
        delta = last_article - first_article
        average = round(float(len(articles)) / abs(delta.days), 2)
    except:
        last_article = datetime.fromtimestamp(0)
        first_article = datetime.fromtimestamp(0)
        delta = last_article - first_article
        average = 0
    elapsed = today - last_article

    return render_template('feed.html',
                           head_titles=[utils.clear_string(feed.title)],
                           feed=feed, tag_cloud=tag_cloud,
                           first_post_date=first_article,
                           end_post_date=last_article,
                           average=average, delta=delta, elapsed=elapsed)


@feed_bp.route('/delete/<feed_id>', methods=['GET'])
@login_required
def delete(feed_id=None):
    feed_contr = FeedController(g.user.id)
    feed = feed_contr.get(id=feed_id)
    feed_contr.delete(feed_id)
    flash(gettext("Feed %(feed_title)s successfully deleted.",
                  feed_title=feed.title), 'success')
    return redirect(url_for('home'))


@feed_bp.route('/reset_errors/<int:feed_id>', methods=['GET', 'POST'])
@login_required
def reset_errors(feed_id):
    feed_contr = FeedController(g.user.id)
    feed = feed_contr.get(id=feed_id)
    feed_contr.update({'id': feed_id}, {'error_count': 0, 'last_error': ''})
    flash(gettext('Feed %(feed_title)r successfully updated.',
                  feed_title=feed.title), 'success')
    return redirect(request.referrer or url_for('home'))


@feed_bp.route('/bookmarklet', methods=['GET'])
@login_required
def bookmarklet():
    feed_contr = FeedController(g.user.id)
    url = request.args.get('url', None)
    if not url:
        flash(gettext("Couldn't add feed: url missing."), "error")
        raise BadRequest("url is missing")

    feed_exists = list(feed_contr.read(__or__={'link': url, 'site_link': url}))
    if feed_exists:
        flash(gettext("Couldn't add feed: feed already exists."),
                "warning")
        return redirect(url_for('feed.form', feed_id=feed_exists[0].id))

    try:
        feed = construct_feed_from(url)
    except requests.exceptions.ConnectionError:
        flash(gettext("Impossible to connect to the address: {}.".format(url)),
              "danger")
        return redirect(url_for('home'))
    if not feed.get('link'):
        feed['enabled'] = False
        flash(gettext("Couldn't find a feed url, you'll need to find a Atom or"
                      " RSS link manually and reactivate this feed"),
              'warning')
    feed = feed_contr.create(**feed)
    flash(gettext('Feed was successfully created.'), 'success')
    if feed.enabled and conf.CRAWLING_METHOD == "classic":
        utils.fetch(g.user.id, feed.id)
        flash(gettext("Downloading articles for the new feed..."), 'info')
    return redirect(url_for('feed.form', feed_id=feed.id))


@feed_bp.route('/update/<action>/<int:feed_id>', methods=['GET', 'POST'])
@feeds_bp.route('/update/<action>', methods=['GET', 'POST'])
@login_required
def update(action, feed_id=None):
    readed = action == 'read'
    filters = {'readed__ne': readed}

    nb_days = request.args.get('nb_days', 0, type=int)
    if nb_days != 0:
        filters['date__lt'] = datetime.now() - timedelta(days=nb_days)

    if feed_id:
        filters['feed_id'] = feed_id
    ArticleController(g.user.id).update(filters, {'readed': readed})
    flash(gettext('Feed successfully updated.'), 'success')
    return redirect(request.referrer or url_for('home'))


@feed_bp.route('/create', methods=['GET'])
@feed_bp.route('/edit/<int:feed_id>', methods=['GET'])
@login_required
@etag_match
def form(feed_id=None):
    action = gettext("Add a feed")
    head_titles = [action]
    if feed_id is None:
        return render_template('edit_feed.html', action=action,
                               head_titles=head_titles, form=AddFeedForm())
    feed = FeedController(g.user.id).get(id=feed_id)
    action = gettext('Edit feed')
    head_titles = [action]
    if feed.title:
        head_titles.append(feed.title)
    return render_template('edit_feed.html', action=action,
                           head_titles=head_titles,
                           form=AddFeedForm(obj=feed), feed=feed)


@feed_bp.route('/create', methods=['POST'])
@feed_bp.route('/edit/<int:feed_id>', methods=['POST'])
@login_required
def process_form(feed_id=None):
    form = AddFeedForm()
    feed_contr = FeedController(g.user.id)

    if not form.validate():
        return render_template('edit_feed.html', form=form)
    existing_feeds = list(feed_contr.read(link=form.link.data))
    if existing_feeds and feed_id is None:
        flash(gettext("Couldn't add feed: feed already exists."), "warning")
        return redirect(url_for('feed.form', feed_id=existing_feeds[0].id))
    # Edit an existing feed
    feed_attr = {'title': form.title.data, 'enabled': form.enabled.data,
                 'link': form.link.data, 'site_link': form.site_link.data,
                 'filters': []}

    for filter_attr in ('type', 'pattern', 'action on', 'action'):
        for i, value in enumerate(
                request.form.getlist(filter_attr.replace(' ', '_'))):
            if i >= len(feed_attr['filters']):
                feed_attr['filters'].append({})
            feed_attr['filters'][i][filter_attr] = value

    if feed_id is not None:
        feed_contr.update({'id': feed_id}, feed_attr)
        flash(gettext('Feed %(feed_title)r successfully updated.',
                      feed_title=feed_attr['title']), 'success')
        return redirect(url_for('feed.form', feed_id=feed_id))

    # Create a new feed
    new_feed = FeedController(g.user.id).create(**feed_attr)

    flash(gettext('Feed %(feed_title)r successfully created.',
                  feed_title=new_feed.title), 'success')

    if conf.CRAWLING_METHOD == "classic":
        utils.fetch(g.user.id, new_feed.id)
        flash(gettext("Downloading articles for the new feed..."), 'info')

    return redirect(url_for('feed.form', feed_id=new_feed.id))

pyaggr3g470r/views/icon.py
import base64
from flask import Blueprint, Response, request
from pyaggr3g470r.controllers import IconController
from pyaggr3g470r.lib.view_utils import etag_match

icon_bp = Blueprint('icon', __name__, url_prefix='/icon')

@icon_bp.route('/', methods=['GET'])
@etag_match
def icon():
    icon = IconController().get(url=request.args['url'])
    headers = {'Cache-Control': 'max-age=86400',
               'Content-Type': icon.mimetype}
    return Response(base64.b64decode(icon.content), headers=headers)

pyaggr3g470r/templates/feed_list.html
{% if feeds.all()| count == 0 %}
  <h1>{{_("No feed")}}</h1>
{% else %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ _('Status') }}</th>
                <th>{{ _('Title') }}</th>
                <th>{{ _('Site') }}</th>
                <th>{{ _('Articles') }}</th>
                <th>{{ _('Actions') }}</th>
            </tr>
        </thead>
        <tbody>
        {% for feed in feeds|sort(attribute="title") %}
            <tr {% if not feed.enabled  %}class="warning"{% endif %}>
                <td>{{ loop.index }}</td>
                <td>
                    {% if feed.enabled  %}
                        <i class="glyphicon glyphicon-eye-open" title="{{ _('Feed enabled') }}"></i>
                    {% else %}
                        <i class="glyphicon glyphicon-eye-close" title="{{ _('Feed disabled') }}"></i>
                    {% endif %}
                    {% if feed.error_count >= conf.DEFAULT_MAX_ERROR %}
                        <i class="glyphicon glyphicon-exclamation-sign" title="{{ _('Feed encountered too much errors.') }}"></i>
                    {% endif %}
                </td>
                <td><a href="{{ url_for("feed.feed", feed_id=feed.id) }}" {% if feed.description %}title="{{ feed.description  }}"{% endif %}>
                    {% if feed.icon_url %}<img src="{{ url_for('icon.icon', url=feed.icon_url) }}" width="16px" />{% endif %}
                    {{ feed.title }}
                </a></td>
                <td><a href="{{ feed.site_link }}">{{ feed.site_link }}</a></td>
                <td>( {{ unread_article_count.get(feed.id, 0) }} ) {{ article_count.get(feed.id, 0) }}</td>
                <td>
                    <a href="{{ url_for("home", feed_id=feed.id, filter_="all") }}"><i class="glyphicon glyphicon-th-list" title="{{ _('Articles') }}"></i></a>
                    <a href="{{ url_for("feed.form", feed_id=feed.id) }}"><i class="glyphicon glyphicon-edit" title="{{ _('Edit this feed') }}"></i></a>
                    <a href="/duplicates/{{ feed.id }}"><i class="glyphicon glyphicon-book" title="{{ _('Duplicate articles') }}"></i></a>
                    <a href="{{ url_for("feed.delete", feed_id=feed.id) }}"><i class="glyphicon glyphicon-remove" title="{{ _('Delete this feed') }}" onclick="return confirm('{{ _('You are going to delete this feed.') }}');"></i></a>
                </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

pyaggr3g470r/templates/feeds.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <h1>{{ _('You are subscribed to') }} {{ feeds.count() }} {{ _('feeds') }} &middot; {{ _('Add a') }} <a href="{{ url_for("feed.form") }}">{{ _('feed') }}</a></h1>
    {% include "feed_list.html" %}
</div><!-- /.container -->
{% endblock %}

pyaggr3g470r/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% if feeds|count == 0 %}
    <div class="col-md-4 col-md-offset-4">
        <h1>{{ _("You don't have any feeds.") }}</h1>
        <h1><a href="{{ url_for("feed.form") }}">{{ _('Add some') }}</a>, {{ _('or') }} <a href="/management">{{ _('upload an OPML file.') }}</a></h1>
    </div>
{% else %}
<div class="container-fluid">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-md-2 sidebar sidebar-offcanvas pre-scrollable affix hidden-sm hidden-xs" id="sidebar" role="navigation" data-spy="affix" style="max-height: 100%;">
            <ul class="nav nav-sidebar" data-offset-top="0" data-offset-bottom="0">
                <li><a href="{{ gen_url(feed_id=0) }}">
                    {% if not feed_id %}<b>{% endif %}
                    {{ _('All feeds') }} <span id="total-unread" class="badge pull-right">{{ articles.__len__() }}</span>
                    {% if not feed_id %}</b>{% endif %}
                </a></li>
            {% for fid, nbunread in unread|dictsort(by='value')|reverse %}
                <li class="feed-menu"><a href="{{ gen_url(feed_id=fid) }}">
                    {% if feed_id == fid %}<b>{% endif %}
                        {% if in_error.get(fid, 0) > 0 %}
                            <span style="background-color: {{ "red" if in_error[fid] > conf.DEFAULT_MAX_ERROR -1 else "orange" }} ;" class="badge pull-right" title="Some errors occured while trying to retrieve that feed.">{{ in_error[fid] }} {{ _("error") }}{% if in_error[fid] > 1 %}s{% endif %}</span>
                        {% endif %}
                        <span id="unread-{{ fid }}" class="badge pull-right">{{ nbunread }}</span>
                        {{ feeds[fid]|safe }}
                    {% if feed_id == fid %}</b>{% endif %}
                </a></li>
                <li class="feed-commands"><span>
                    <a href="/feed/{{ fid }}"><i class="glyphicon glyphicon-info-sign" title="{{ _('Details') }}"></i></a>
                    <a href="{{ url_for("feed.form", feed_id=fid) }}"><i class="glyphicon glyphicon-edit" title="{{ _('Edit this feed') }}"></i></a>
                    <a href="{{ url_for("feed.delete", feed_id=fid) }}"><i class="glyphicon glyphicon-remove" title="{{ _('Delete this feed') }}" onclick="return confirm('{{ _('You are going to delete this feed.') }}');"></i></a>
                    <a href="{{ url_for("feed.update", feed_id=fid, action="read") }}"><i class="glyphicon glyphicon-check" title="{{ _('Mark this feed as read') }}"></i></a>
                    <a href="{{ url_for("feed.update", feed_id=fid, action="unread") }}"><i class="glyphicon glyphicon-unchecked" title="{{ _('Mark this feed as unread') }}"></i></a>
                </span></li>
            {% endfor %}
            {% for fid, ftitle in feeds|dictsort(case_sensitive=False, by='value') if not fid in unread %}
                <li class="feed-menu"><a href="{{ gen_url(feed_id=fid) }}">
                    {% if in_error.get(fid, 0) > 0 %}
                        <span style="background-color: {{ "red" if in_error[fid] > conf.DEFAULT_MAX_ERROR - 1 else "orange" }} ;" class="badge pull-right" title="Some errors occured while trying to retrieve that feed.">{{ in_error[fid] }} {{ _("error") }}{% if in_error[fid] > 1 %}s{% endif %}</span>
                    {% endif %}
                    {% if feed_id == fid %}<b>{% endif %}
                        {{ ftitle|safe }}
                    {% if feed_id == fid %}</b>{% endif %}
                </a></li>
                <li class="feed-commands"><span>
                    <a href="{{ url_for("feed.feed", feed_id=fid) }}"><i class="glyphicon glyphicon-info-sign" title="{{ _('Details') }}"></i></a>
                    <a href="{{ url_for("feed.form", feed_id=fid) }}"><i class="glyphicon glyphicon-edit" title="{{ _('Edit this feed') }}"></i></a>
                    <a href="{{ url_for("feed.delete", feed_id=fid) }}"><i class="glyphicon glyphicon-remove" title="{{ _('Delete this feed') }}" onclick="return confirm('{{ _('You are going to delete this feed.') }}');"></i></a>
                    <a href="{{ url_for("feed.update", feed_id=fid, action="read") }}"><i class="glyphicon glyphicon-check" title="{{ _('Mark this feed as read') }}"></i></a>
                    <a href="{{ url_for("feed.update", feed_id=fid, action="unread") }}"><i class="glyphicon glyphicon-unchecked" title="{{ _('Mark this feed as unread') }}"></i></a>
                </span></li>
            {% endfor %}
            </ul>
        </div><!-- row -->

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="col-md-offset-2 col-md-10 main">
                    {% block messages %}
                        {{ super() }}
                    {% endblock %}
                </div>
            {% endif %}
        {% endwith %}
        <div class="col-md-offset-2 col-md-10 main">
            <div id="filters" data-filter="{{ filter_ }}">
                <ul id="myTab" class="nav nav-tabs" role="tablist">
                    <li id="tab-all"><a href="{{ gen_url(filter_='all') }}">{{ _('All') }}</a></li>
                    <li id="tab-read"><a href="{{ gen_url(filter_='read') }}">{{ _('Read') }}</a></li>
                    <li id="tab-unread"><a href="{{ gen_url(filter_='unread') }}">{{ _('Unread') }}</a></li>
                    <li id="tab-nbdisplay" class="pull-right">
                        <div id="nbdisplay">
                            <a href="{{ gen_url(limit=10) }}" class="label {% if limit == 10 %}label-primary{% else %}label-info{% endif %}">{{ _(10) }}</a>
                            <a href="{{ gen_url(limit=100) }}" class="label {% if limit == 100 %}label-primary{% else %}label-info{% endif %}">{{ _(100) }}</a>
                            <a href="{{ gen_url(limit=1000) }}" class="label {% if limit == 1000 %}label-primary{% else %}label-info{% endif %}">{{ _(1000) }}</a>
                            <a href="{{ gen_url(limit='all') }}" class="label {% if limit == 'all' %}label-primary{% else %}label-info{% endif %}">{{ _('All') }}</a>
                        </div>
                    </li>
            </div>
            {% if articles | count != 0%}
                <div class="table-responsive">
                    <table class="table table-striped strict-table">
                        <thead>
                            <tr>
                                <th></th>
                                <th><a href="{{ gen_url(sort_='-feed' if sort_ == 'feed' else 'feed') }}">{{ _('Feed') }}</a></th>
                                <th><a href="{{ gen_url(sort_='-article' if sort_ == 'article' else 'article') }}">{{ _('Article') }}</a></th>
                                <th><a href="{{ gen_url(sort_='-date' if sort_ == 'date' else 'date') }}">{{ _('Date') }}</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for article in articles %}
                            <tr data-article="{{ article.id }}" data-feed="{{ article.feed_id }}">
                                <td>
                                    <a><i class="glyphicon glyphicon-remove delete" title="{{ _('Delete this article') }}"></i></a>
                                    {% if article.like %}
                                        <a><i class="glyphicon glyphicon-star like" title="{{ _('One of your favorites') }}"></i></a>
                                    {% else %}
                                        <a><i class="glyphicon glyphicon-star-empty like" title="{{ _('Click if you like this article') }}"></i></a>
                                    {% endif %}
                                    {% if article.readed %}
                                        <a><i class="glyphicon glyphicon-unchecked readed" title="{{ _('Mark this article as unread') }}"></i></a>
                                    {% else %}
                                        <a><i class="glyphicon glyphicon-check readed" title="{{ _('Mark this article as read') }}"></i></a>
                                        {% if filter_ == 'all' %}</b>{% endif %}
                                    {% endif %}
                                </td>
                                <td>
                                    <a class="open-article" href="{{ url_for("article.redirect_to_article", article_id=article.id)}}" target="_blank" title="{{article.link}}" alt="{{article.link}}">
                                  {% if article.source.icon_url %}
                                    <img src="{{ url_for('icon.icon', url=article.source.icon_url) }}" width="16px" />
                                  {% else %}
                                    <span class="glyphicon glyphicon-ban-circle" title='{{_("No icon found for this feed")}}' alt='{{_("No icon found for this feed")}}'></span>
                                  {% endif %}
                                  <span class="hidden-xs">{{ article.source.title|safe }}</span></a></td>
                                <td {%if filter_ == 'all' and article.readed == False %}style='font-weight:bold'{% endif %}>
                                    <a href="{{ url_for("article.article", article_id=article.id) }}">{{ article.title|safe }}</a>
                                </td>
                                <td class="date">{{ article.date|datetime }}</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div><!-- row -->
    </div><!-- main -->
</div><!-- container-fluid -->
<style>.not-at-home {display: none};</style>
{% endif %}
{% endblock %}

pyaggr3g470r/templates/inactives.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="well">
        <form method=get action="/inactives">
            <p>{{ _('Days of inactivity') }}:</p>
            <input type="number" name="nb_days" class="form-control" value="{{ nb_days }}" min="0" max="1000000" step="1" size="4" style="text-align: center" />
        </form>
        <br />
        {% if inactives != [] %}
            <ul class="list-group">
            {% for feed, delta in inactives %}
                <li class="list-group-item">
                    <a href="{{ url_for('feed.feed', feed_id=feed.id) }}">
                        {% if feed.icon %}<img src="{{ url_for('feed.icon', feed_id=feed.id) }}" width="16px" />{% endif %}
                        {{ feed.title }}
                    </a> - {{ delta.days }} {{ _('days') }}
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>{{ _('No inactive feeds.') }}<p>
        {% endif %}
    </div>
</div><!-- /.container -->
{% endblock %}